### ISSUE TITLE
Possible Unicode characters parsing error

### ISSUE THREAD

**Issue by nextPrime** [MicrosoftEdge/css-usage#28]
On the [font family usage page](https://developer.microsoft.com/en-us/microsoft-edge/platform/usage/css/font-family/), you can see Unicode replacement character (��, �S, �o��, etc.) under "Distribution of popular font-family values" section -> "Show More"->the line after "oswald". Does this indicate that the crawler doesn't understand some Unicode encoding on the web pages?

**Comment by FremyCompany** [comment]
Yes, something in our Edge data pipeline in particular does not seem to return proper values when Unicode is used to define font names. Not sure this is a huge deal, though, because we actually do not care about those values. Strings and identifiers are being anonymized in other places, so this only have an impact on font-family, as far as I know.

Do you see this being an issue for something important?

**Comment by nextPrime** [comment]
> Do you see this being an issue for something important?

No. I found this issue when I was randomly browsing the usage pages, and was curious what these values should be. Feel free to close as won't fix, if this is not so important for you.

**Comment by FremyCompany** [comment]
Ok, let's close the issue for now. We can always revisit if we find the issue to affect something else than font names. Thanks for taking the time to report it, though.
